version: '3'
services:
  app:
    build:
      context: ./docker-laravel/app
      dockerfile: ./docker-laravel/app/app1-laravel.Dockerfile
    image: huenisys/app1-laravel:latest
    networks:
      - appnet
    volumes:
      - ${PWD}/persistence/storage:/home/huenisys/application/storage
      - ${PWD}/laravel:/home/huenisys/application
      - ${PWD}/persistence/.env:/home/huenisys/application/.env
    ports:
      - ${APP_PORT}:80
    working_dir: /home/huenisys/application
  cache:
    build:
      context: ./docker-laravel
      dockerfile: ./docker-laravel/cache-laravel.Dockerfile
    image: huenisys/cache-laravel:latest
    networks:
      - appnet
    volumes:
      - cachedata:/data
  nodejs:
    build:
      context: ./docker-laravel
      dockerfile: ./docker-laravel/nodejs-laravel.Dockerfile
    image: huenisys/nodejs-laravel:latest
    networks:
      - appnet
    volumes:
      - ./laravel:/home/node/application
    working_dir: /home/node/application
    command: bash -c "echo -n 'node version ' && node -v"
  db:
    build:
      context: ./docker-laravel
      dockerfile: ./docker-laravel/db-laravel.Dockerfile
    image: huenisys/db-laravel:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
