version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: ./docker/app/Dockerfile
    image: huenisys/app1:latest
    networks:
      - appnet
    volumes:
      - .:/home/huenisys/application
    ports:
      - ${APP_PORT}:80
    working_dir: /home/huenisys/application
  cache:
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data
  nodejs:
    build:
      context: ./docker/nodejs
      dockerfile: ./docker/nodejs/Dockerfile
    image: huenisys/nodejs:latest
    networks:
      - appnet
    volumes:
      - .:/home/node/application
    working_dir: /home/node/application
    command: bash -c "echo -n 'node version ' && node -v"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - ${DB_PORT}:3306
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
